name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular build com sucesso
        run: echo "Build OK"